const services = [
  {
    id: '1',
    showId: '1',
    type: 'rehearsal',
    date: new Date(2023, 10, 12),
    startTime: '7:30',
    endTime: '10:00',
    location: 'Warner Theater',
  },
  {
    id: '2',
    showId: '1',
    type: 'rehearsal',
    date: new Date(2023, 10, 13),
    startTime: '7:30',
    endTime: '10:00',
    location: 'Warner Theater',
  },
  {
    id: '3',
    showId: '1',
    type: 'rehearsal',
    date: new Date(2023, 10, 14),
    startTime: '7:30',
    endTime: '10:00',
    location: 'Warner Theater',
  },
  { id: '4', showId: '1', type: 'concert', date: new Date(2023, 10, 19), startTime: '8:00', location: 'Warner Theater' },
  {
    id: '5',
    showId: '2',
    type: 'rehearsal',
    date: new Date(2023, 11, 12),
    startTime: '7:30',
    endTime: '10:00',
    location: 'Warner Theater',
  },
  {
    id: '6',
    showId: '2',
    type: 'rehearsal',
    date: new Date(2023, 11, 13),
    startTime: '7:30',
    endTime: '10:00',
    location: 'Warner Theater',
  },
  {
    id: '7',
    showId: '2',
    type: 'rehearsal',
    date: new Date(2023, 11, 14),
    startTime: '7:30',
    endTime: '10:00',
    location: 'Warner Theater',
  },
  { id: '8', showId: '2', type: 'concert', date: new Date(2023, 11, 15), startTime: '8:00', location: 'Cole Auditorium' },
];

export default services;
